### PR TITLE
8279368: [lworld] Add parser support for declaration of value classes

### PR DESCRIPTION
**Pull request by sadayapalam**
Enhance the parser to accept value class declarations

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8279368](https://bugs.openjdk.java.net/browse/JDK-8279368): [lworld] Add parser support for declaration of value classes

### Reviewers
 * @biboudis (no known github.com user name / role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/596/head:pull/596` \
`$ git checkout pull/596`

Update a local copy of the PR: \
`$ git checkout pull/596` \
`$ git pull https://git.openjdk.java.net/valhalla pull/596/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 596`

View PR using the GUI difftool: \
`$ git pr show -t 596`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/596.diff">https://git.openjdk.java.net/valhalla/pull/596.diff</a>

</details>

### CODE REVIEW

**Comment by sadayapalam** [comment]
Notes for reviewer:

Notes:

    - This patch ddds support for value classes in the parser
      using the value modifier or the __value__ annotation 
      (latter is temporary untils IDEs support value modifier)

    - All that happens at the moment is, value class syntax is
      digested and a value classe is flagged as being one by 
      virtue of setting the Flags.VALUE_CLASS bit.

    - This bit itself is "dropped" (ignored) by subsequent stages
      of the pipeline as of now

    - Feature support base version level bumped up to 18

    - Introduce the class file symbolic constant ACC_VALUE (0x100)

    - Contains a bug fix - sometimes we were not emitting the best
      message for use of primitive/value classes with an inappropriate
      source level (instead of complaining "primitive/value classes are
      not supported in -source 17" we were instead complaining 
      "warning: 'primitive' may become a restricted type name in future"

    - Fixed a singular -> plural grammar issue in diagnostics.

**Comment by biboudis** [comment]
This looks good to me 💯

I believe the following observations are not related to this PR so I am accepting it, but I would like to hear what you think:

1. `public native value class FooTest { }` passes but also `public native class FooTest { }`. `native` shouldn't be applicable here at all here I think.

2. An inconsistency in error reporting:

```
FooTest.java:2: error: repeated modifier
public native native class FooTest { }
              ^
```

but:
```
FooTest.java:2: error: class, interface, enum, or record expected
public value value class FooTest { }
       ^
```

What do you think?

**Review by biboudis — APPROVED** [review]

**Comment by sadayapalam** [comment]
Thanks Aggelos, both observations are valid and I will raise follow up tickets to tackle them.

**Pull request closed without merging**
