### PR TITLE
Merge lworld

### PR DESCRIPTION
**Pull request by XiaohongGong**
This patch merges the latest `valhalla:lworld` to
 `valhalla:lworld+vector` branch, together with following
 main changes:

1. Resolve conflicts mainly caused by the BACKOUT of
 `VectorShuffle refactory` in jdk mainline [1].
2. Fix the class id issue for `SafePointScalarMergeNode` added by [JDK-8287061](https://bugs.openjdk.java.net/browse/JDK-8287061). This causes an jvm crash
 when building the jdk image. `lworld` branch also
 fixes it (see [2]), but it seems the id is not correctly
 ordered.

[1] https://github.com/openjdk/jdk/pull/14629

[2] https://github.com/openjdk/valhalla/blob/lworld/src/hotspot/share/opto/node.hpp#L738

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Jatin Bhateja](https://openjdk.org/census#jbhateja) (@jatin-bhateja - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/921/head:pull/921` \
`$ git checkout pull/921`

Update a local copy of the PR: \
`$ git checkout pull/921` \
`$ git pull https://git.openjdk.org/valhalla.git pull/921/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 921`

View PR using the GUI difftool: \
`$ git pr show -t 921`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/921.diff">https://git.openjdk.org/valhalla/pull/921.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/921#issuecomment-1698556369)

### CODE REVIEW

**Comment by jatin-bhateja** [comment]
Hi @XiaohongGong , 

I verified that validation status is intact and other failures with additional -XX:+DeoptimizeALot option are also fixed with the merge.

Best Regards,
Jatin

**Review by jatin-bhateja — APPROVED** [review]

**Comment by XiaohongGong** [comment]
> Hi @XiaohongGong ,
> 
> I verified that validation status is intact and other failures with additional -XX:+DeoptimizeALot option are also fixed with the merge.
> 
> Best Regards, Jatin

Thanks for the review and testing @jatin-bhateja ! Did you see any other regressions on Vector API tests with this option? I also ran the tests with `-XX:+DeoptimizeALot`, but some regressions that I met before are still there on NEON.  I remembered that some x86 specific code was changed (i.e. https://github.com/openjdk/valhalla/commit/d9f744fe6e816a91aa7c8d5e84ce464e8a9d3921#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897), which is missing on AArch64 platform now. Seems this can also influence the result in interpreter, right? I will have a test by adding the similar code on AArch64 again. 

Best Regards,
Xiaohong

**Comment by XiaohongGong** [comment]
> 

Unfortunately, the regressions are still there even with the AArch64 changes. One of the log is:
```
test Int128VectorTests.GEInt128VectorTestsMasked(int[i], int[i], mask[i % 2]): failure
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertEqualsImpl(Assert.java:140)
        at org.testng.Assert.assertEquals(Assert.java:122)
        at org.testng.Assert.assertEquals(Assert.java:819)
        at org.testng.Assert.assertEquals(Assert.java:829)
        at Int128VectorTests.GEInt128VectorTestsMasked(Int128VectorTests.java:4176)
```
Anyway, this is not invoked by this merge, and I will revisit the regressions in furure.

**Comment by jatin-bhateja** [comment]
> > Hi @XiaohongGong ,
> > I verified that validation status is intact and other failures with additional -XX:+DeoptimizeALot option are also fixed with the merge.
> > Best Regards, Jatin
> 
> Thanks for the review and testing @jatin-bhateja ! Did you see any other regressions on Vector API tests with this option? I also ran the tests with `-XX:+DeoptimizeALot`, but some regressions that I met before are still there on NEON. I remembered that some x86 specific code was changed (i.e. [d9f744f#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897](https://github.com/openjdk/valhalla/commit/d9f744fe6e816a91aa7c8d5e84ce464e8a9d3921#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897)), which is missing on AArch64 platform now. Seems this can also influence the result in interpreter, right? I will have a test by adding the similar code on AArch64 again.
> 
> Best Regards, Xiaohong

Failures related to shuffle/mask in *LoadStoreTests.java are no longer seen with merge. Overall validation status improved when compared with pre-merge state. Do you see any new failures introduced with merge ?

If not can we integrate this patch and then fix the outstand regressions.

Best Regards,
Jatin

**Comment by jatin-bhateja** [comment]
> > Hi @XiaohongGong ,
> > I verified that validation status is intact and other failures with additional -XX:+DeoptimizeALot option are also fixed with the merge.
> > Best Regards, Jatin
> 
> Thanks for the review and testing @jatin-bhateja ! Did you see any other regressions on Vector API tests with this option? I also ran the tests with `-XX:+DeoptimizeALot`, but some regressions that I met before are still there on NEON. I remembered that some x86 specific code was changed (i.e. [d9f744f#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897](https://github.com/openjdk/valhalla/commit/d9f744fe6e816a91aa7c8d5e84ce464e8a9d3921#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897)), which is missing on AArch64 platform now. Seems this can also influence the result in interpreter, right? I will have a test by adding the similar code on AArch64 again.
> 
> Best Regards, Xiaohong

Yes, this can impact test failures since VectorPayload* constructors return a value object and we do not want to scalarize it, by default values are flattened using unpacking handlers.

**Comment by XiaohongGong** [comment]
> > > Hi @XiaohongGong ,
> > > I verified that validation status is intact and other failures with additional -XX:+DeoptimizeALot option are also fixed with the merge.
> > > Best Regards, Jatin
> > 
> > 
> > Thanks for the review and testing @jatin-bhateja ! Did you see any other regressions on Vector API tests with this option? I also ran the tests with `-XX:+DeoptimizeALot`, but some regressions that I met before are still there on NEON. I remembered that some x86 specific code was changed (i.e. [d9f744f#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897](https://github.com/openjdk/valhalla/commit/d9f744fe6e816a91aa7c8d5e84ce464e8a9d3921#diff-a47d36f3d2e8997bd3d2320ef348dd17b91f388d2cb6e91e9d99d66df5ccd897)), which is missing on AArch64 platform now. Seems this can also influence the result in interpreter, right? I will have a test by adding the similar code on AArch64 again.
> > Best Regards, Xiaohong
> 
> Failures related to shuffle/mask in *LoadStoreTests.java are no longer seen with merge. Overall validation status improved when compared with pre-merge state. Do you see any new failures introduced with merge ?
> 
> If not can we integrate this patch and then fix the outstand regressions.
> 
> Best Regards, Jatin

No new regressions are involved by this merge. I will integrate this patch first. Thanks!

**Pull request closed without merging**
