### PR TITLE
8334692: [lworld] add missing compiler warnings

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
adding warning for value classes declaring a `finalize` method and warnings related to the new serialization

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8334692](https://bugs.openjdk.org/browse/JDK-8334692): [lworld] add missing compiler warnings (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/1147/head:pull/1147` \
`$ git checkout pull/1147`

Update a local copy of the PR: \
`$ git checkout pull/1147` \
`$ git pull https://git.openjdk.org/valhalla.git pull/1147/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1147`

View PR using the GUI difftool: \
`$ git pr show -t 1147`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/1147.diff">https://git.openjdk.org/valhalla/pull/1147.diff</a>

</details>

### CODE REVIEW

**Comment by RogerRiggs** [comment]
The bug closed as a duplicate intended to add a javadoc note on the non-applicability of finalize to value objects.
I had added a comment to 8334692, to make sure it didn't get missed.

**Comment by vicente-romero-oracle** [comment]
> The bug closed as a duplicate intended to add a javadoc note on the non-applicability of finalize to value objects. I had added a comment to 8334692, to make sure it didn't get missed.

true, I had a note for that, I forgot sorry

**Pull request closed without merging**
