### PR TITLE
8329108: [lworld] valhalla/valuetypes/ObjectMethods.java fails with default CDS archive

### PR DESCRIPTION
**Pull request by matias9927**
When this test was run after `java -Xshare:dump --enable-preview`, the test would crash due to a null signature calling convention. This occurred because `has_scalarized_args`, a flag whose value should be determined at runtime when regenerating the method adapter, was stored in ConstMethod and then archived. The resulting mismatch in a subsequent run meant the wrong `sig_cc` would be used. This change moves the flags in question into `method.hpp` and avoids dumping them so they can be properly regenerated at runtime. The test was verified locally and the changes were further verified with tier 1-5 tests.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8329108](https://bugs.openjdk.org/browse/JDK-8329108): [lworld] valhalla/valuetypes/ObjectMethods.java fails with default CDS archive (**Bug** - P2)

### Reviewers
 * [David Simms](https://openjdk.org/census#dsimms) (@MrSimms - Committer)
 * [Frederic Parain](https://openjdk.org/census#fparain) (@fparain - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/1180/head:pull/1180` \
`$ git checkout pull/1180`

Update a local copy of the PR: \
`$ git checkout pull/1180` \
`$ git pull https://git.openjdk.org/valhalla.git pull/1180/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1180`

View PR using the GUI difftool: \
`$ git pr show -t 1180`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/1180.diff">https://git.openjdk.org/valhalla/pull/1180.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/1180#issuecomment-2248917737)

### CODE REVIEW

**Review by MrSimms — APPROVED** [review]
LGTM

**Review by fparain — APPROVED** [review]
LGTM
Thank you for the investigation you did on this bug.

**Comment by matias9927** [comment]
Thanks for the reviews @MrSimms and @fparain!
/integrate

**Pull request closed without merging**
