### PR TITLE
8329218: [lworld] Arrays.copyOf and Arrays.copyOfRange support for null-restricted arrays

### PR DESCRIPTION
**Pull request by mlchung**
`Arrays::copyOf` and `Arrays::copyOfRange` should return a null-restricted array if the input array is null-restricted.   The intrinsification for these methods will need to be updated ([JDK-8329218](https://bugs.openjdk.org/browse/JDK-8329218)).  Three test cases in `test/hotspot/jtreg/compiler/valhalla/inlinetypes/TestArrays.java` are commented out until JDK-8329218 is resolved.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8329218](https://bugs.openjdk.org/browse/JDK-8329218): [lworld] Arrays.copyOf and Arrays.copyOfRange support for null-restricted arrays (**Enhancement** - P4)

### Reviewers
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/1070/head:pull/1070` \
`$ git checkout pull/1070`

Update a local copy of the PR: \
`$ git checkout pull/1070` \
`$ git pull https://git.openjdk.org/valhalla.git pull/1070/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1070`

View PR using the GUI difftool: \
`$ git pr show -t 1070`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/1070.diff">https://git.openjdk.org/valhalla/pull/1070.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/1070#issuecomment-2035049719)

### CODE REVIEW

**Comment by mlchung** [comment]
I should clarify.  This change is to enable valhalla tests to continue to use `Arrays::copyOf` for null-restricted arrays.  It's solely implementation change.     lworld does not have the compiler and class file support for null-restricted types which is a separate JEP.   No public API for null-restricted arrays.

To create a null-restricted array, it has to use `jdk.internal.value.ValueClass::newNullRestrictedArray` and `CheckedType` and `NullRestrictedCheckedType` are internal APIs.   `System.arraycopy` should already work for null-restricted arrays.

**Comment by mlchung** [comment]
As of now, the class mirror is the same for normal and null-restricted array.

**Comment by liach** [comment]
Thanks for the explanations. I was curious that the current copyOf implementation doesn't allow specifying if the new array should be NR or not.

**Review by RogerRiggs — APPROVED** [review]
LGTM

**Pull request closed without merging**
