### PR TITLE
Merge lworld

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Merge from lworld into lworld+vector.

Please review and approve.

Best Regards,
Jatin

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Xiaohong Gong](https://openjdk.org/census#xgong) (@XiaohongGong - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/847/head:pull/847` \
`$ git checkout pull/847`

Update a local copy of the PR: \
`$ git checkout pull/847` \
`$ git pull https://git.openjdk.org/valhalla.git pull/847/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 847`

View PR using the GUI difftool: \
`$ git pr show -t 847`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/847.diff">https://git.openjdk.org/valhalla/pull/847.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/847#issuecomment-1551453961)

### CODE REVIEW

**Comment by jatin-bhateja** [comment]
Hi @TobiHartmann ,
Can you kindly sponsor the patch.

Best Regards,
Jatin

**Review by XiaohongGong — APPROVED** [review]
LGTM!

**Comment by XiaohongGong** [comment]
Hi @jatin-bhateja , could you please rebase this PR and resolve the conflicts, so that we can let this merge in as soon as possible? Thanks! I also tried to applied this merge PR and resolve the conflicts locally. But I met new jtreg regression, and I think we can fix it with followed patches after this merge is in. WDYT?

**Comment by jatin-bhateja** [comment]
> Hi @jatin-bhateja , could you please rebase this PR and resolve the conflicts, so that we can let this merge in as soon as possible? Thanks! I also tried to applied this merge PR and resolve the conflicts locally. But I met new jtreg regression, and I think we can fix it with followed patches after this merge is in. WDYT?

Hi @XiaohongGong ,

I am in process of rebasing this merge with latest lworld.
Will update, as discussed any further validations to be done one the merge branch with latest lworld changes on top of your changes.

Best Regards,
Jatin

**Comment by XiaohongGong** [comment]
> > Hi @jatin-bhateja , could you please rebase this PR and resolve the conflicts, so that we can let this merge in as soon as possible? Thanks! I also tried to applied this merge PR and resolve the conflicts locally. But I met new jtreg regression, and I think we can fix it with followed patches after this merge is in. WDYT?
> 
> Hi @XiaohongGong ,
> 
> I am in process of rebasing this merge with latest lworld. Will update, as discussed any further validations to be done on the merge branch with latest lworld code on top of your recently merged changes.
> 
> Best Regards, Jatin

Thanks for the updating! I guess there will be too more conflicts with latest lword branch, like the big `VectorShuffle` refactory. I was planning to do another merge after this one, with the changes to the `VectorShuffle`.  But I'm also fine rebasing this one to the latest lworld. Thanks for doing this!

Best Regards,
Xiaohong

**Comment by jatin-bhateja** [comment]
> > > Hi @jatin-bhateja , could you please rebase this PR and resolve the conflicts, so that we can let this merge in as soon as possible? Thanks! I also tried to applied this merge PR and resolve the conflicts locally. But I met new jtreg regression, and I think we can fix it with followed patches after this merge is in. WDYT?
> > 
> > 
> > Hi @XiaohongGong ,
> > I am in process of rebasing this merge with latest lworld. Will update, as discussed any further validations to be done on the merge branch with latest lworld code on top of your recently merged changes.
> > Best Regards, Jatin
> 
> Thanks for the updating! I guess there will be too more conflicts with latest lword branch, like the big `VectorShuffle` refactory. I was planning to do another merge after this one, with the changes to the `VectorShuffle`. But I'm also fine rebasing this one to the latest lworld. Thanks for doing this!
> 
> Best Regards, Xiaohong

Hi @XiaohongGong ,

There have been significant changes in FieldInfo structure after https://bugs.openjdk.org/browse/JDK-8292818
I again started a new merge since there have been couple of mainline merges into lworld on top of your recently checked in patch related to shuffle and mask handling.

I have appropriately resolved the conflicts related to multifield handling in oops model and plan to withdraw this PR and plan submit a new merge pull request soon.

Best Regards,
Jatin

**Comment by jatin-bhateja** [comment]
Squashing this one and will create a new merge PR.

**Pull request closed without merging**
