### PR TITLE
8277057: [lworld] array code needs some name cleanup

### PR DESCRIPTION
**Pull request by fparain**
Please review this changeset which renames some flags and methods to align them with the current semantics and behavior. Clearer names would help introducing nullable inline types later.

Thank you,

Fred

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8277057](https://bugs.openjdk.java.net/browse/JDK-8277057): [lworld] array code needs some name cleanup

### Reviewers
 * [David Simms](https://openjdk.java.net/census#dsimms) (@MrSimms - Committer) ⚠️ Review applies to b1e6140affe453277fe2521230e1854e7679d792

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/582/head:pull/582` \
`$ git checkout pull/582`

Update a local copy of the PR: \
`$ git checkout pull/582` \
`$ git pull https://git.openjdk.java.net/valhalla pull/582/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 582`

View PR using the GUI difftool: \
`$ git pr show -t 582`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/582.diff">https://git.openjdk.java.net/valhalla/pull/582.diff</a>

</details>

### CODE REVIEW

**Comment by nick-arm** [comment]
I think `c1_LIRAssembler_aarch64.cpp` needs these replacements too.

**Review by MrSimms — APPROVED** [review]
With the addition of c1_LIRAssembler_aarch64.cpp, renaming looks good

**Comment by fparain** [comment]
Nick, David,

Thank you for your reviews.
I've applied the renaming to c1_LIRAssembler_aarch64.cpp and checked the build aarch64 with Mach5.

Fred

**Pull request closed without merging**
