### PR TITLE
8328150: [lworld] Adjust flags to "--enable-preview" clear out EnableValhalla and EnablePrimitiveClasses

### PR DESCRIPTION
**Pull request by MrSimms**
* Removed all cases of -XX: EnableValhalla and EnablePrimitiveClasses
* Deleted tests that were dominated by now defunct concepts (withfield, entirely primitives classes etc)
* Trival fixes to simply remove primitive class tests cases
* `@ignores` tagged with bug number where tests need non-trival updating to JEP401 concepts

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8328150](https://bugs.openjdk.org/browse/JDK-8328150): [lworld] Adjust flags to "--enable-preview" clear out EnableValhalla and EnablePrimitiveClasses (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/1052/head:pull/1052` \
`$ git checkout pull/1052`

Update a local copy of the PR: \
`$ git checkout pull/1052` \
`$ git pull https://git.openjdk.org/valhalla.git pull/1052/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1052`

View PR using the GUI difftool: \
`$ git pr show -t 1052`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/1052.diff">https://git.openjdk.org/valhalla/pull/1052.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/1052#issuecomment-2006729947)

### CODE REVIEW

**Comment by fparain** [comment]
Thank you for this huge cleanup.
Would it make sense to also clean the modules export options?
Many tests use "--add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED --add-exports java.base/jdk.internal.value=ALL-UNNAMED" and those options have to be copied on build, compile, and run commands.
We could let JTREG add those options itself by just adding this to the JTREG tags:

 * @modules java.base/jdk.internal.vm.annotation
 *          java.base/jdk.internal.classfile

**Comment by MrSimms** [comment]
> Thank you for this huge cleanup. Would it make sense to also clean the modules export options? Many tests use "--add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED --add-exports java.base/jdk.internal.value=ALL-UNNAMED" and those options have to be copied on build, compile, and run commands. We could let JTREG add those options itself by just adding this to the JTREG tags:
> 
> ```
>  * @modules java.base/jdk.internal.vm.annotation
>  *          java.base/jdk.internal.classfile
> ```

Totally, good call, let me make another pass

**Comment by fparain** [comment]
I typed the wrong tags, the correct ones are:
```
 * @modules java.base/jdk.internal.vm.annotation
 *          java.base/jdk.internal.value
```

**Pull request closed without merging**
