### PR TITLE
8325343: [lworld] java/lang/reflect/Proxy/ClassRestrictions.java fails with NPE

### PR DESCRIPTION
**Pull request by mlchung**
Trivial 1-line fix is to check if the type is found or not before calling `PrimitiveClass::asPrimaryType`.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8325343](https://bugs.openjdk.org/browse/JDK-8325343): [lworld] java/lang/reflect/Proxy/ClassRestrictions.java fails with NPE (**Bug** - P4)

### Reviewers
 * [Tobias Hartmann](https://openjdk.org/census#thartmann) (@TobiHartmann - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/996/head:pull/996` \
`$ git checkout pull/996`

Update a local copy of the PR: \
`$ git checkout pull/996` \
`$ git pull https://git.openjdk.org/valhalla.git pull/996/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 996`

View PR using the GUI difftool: \
`$ git pr show -t 996`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/996.diff">https://git.openjdk.org/valhalla/pull/996.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/996#issuecomment-1930508698)

### CODE REVIEW

**Comment by TobiHartmann** [comment]
You need to remove the test from the problem list.

**Comment by TobiHartmann** [comment]
See https://github.com/openjdk/valhalla/commit/be6ae3549893cfd67e706d54e23ca414d66084b4

**Comment by mlchung** [comment]
Fixed.  Thanks.

**Review by TobiHartmann — APPROVED** [review]
Looks reasonable to me.

**Pull request closed without merging**
