### PR TITLE
8272041: [lworld] CDS heap dump fails with primitive objects

### PR DESCRIPTION
**Pull request by iklam**
Two simple fixes to handle primitive objects when dumping the CDS heap:

- When dumping the objects, we enter them into a hashtable. Do not use `oopDesc::identity_hash()` as the hashcode for this table.
- When resetting the header of archived objects, do not call `oopDesc::identity_hash()` on primitive objects.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8272041](https://bugs.openjdk.java.net/browse/JDK-8272041): [lworld] CDS heap dump fails with primitive objects

### Reviewers
 * [Frederic Parain](https://openjdk.java.net/census#fparain) (@fparain - Committer)
 * [Mandy Chung](https://openjdk.java.net/census#mchung) (@mlchung - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/525/head:pull/525` \
`$ git checkout pull/525`

Update a local copy of the PR: \
`$ git checkout pull/525` \
`$ git pull https://git.openjdk.java.net/valhalla pull/525/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 525`

View PR using the GUI difftool: \
`$ git pr show -t 525`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/525.diff">https://git.openjdk.java.net/valhalla/pull/525.diff</a>

</details>

### CODE REVIEW

**Review by fparain — APPROVED** [review]
Looks good to me.

Just a question by curiosity, using object addresses instead of the identity hash code is likely to change the distribution of keys for the hashtable (all objects being in the same memory area and being aligned on heap words, some bits in their addresses are the same for all objects). Is it going to have a significant impact of the performance of the hashtable or is it negligeable?

Thank you,

Fred

**Review by mlchung — APPROVED** [review]
Looks good.  I verified with the patch that converts some JDK classes to ref-default primitive class.

**Comment by iklam** [comment]
> Looks good to me.
> 
> Just a question by curiosity, using object addresses instead of the identity hash code is likely to change the distribution of keys for the hashtable (all objects being in the same memory area and being aligned on heap words, some bits in their addresses are the same for all objects). Is it going to have a significant impact of the performance of the hashtable or is it negligeable?

Hi Fred,

Thanks for the review. I've added code to calculate the stats of the hashtable. The max number of entries per bucket is no more than 3, so I think the distribution is acceptable.

Also, the hash function already shifts down by `LogBytesPerWord`, so it will get rid of the lower 3 zero bits.

My stats code is in https://github.com/iklam/valhalla/commits/heap-shared-seen-obj-table-stats, but it's not part of this PR. I will clean it up and integrate into jdk/jdk.

**Comment by iklam** [comment]
Thanks @fparain and @mlchung for the review.
/integrate

**Comment by fparain** [comment]
Ioi,

Thank you for the additional effort to measure statistics of the hashtable.

Fred

**Pull request closed without merging**
