### PR TITLE
8247299: [lworld] Disable UseBiasedLocking by default

### PR DESCRIPTION
**Pull request by MrSimms**
Disabled UseBiasedLocking, and reorganized markWord to serve Valhalla requirements (see also JDK-8247298 for motivation).

Actual UseBiasedLocking code remains simply to avoid future conflicts. Since static constants have changed and UseBiasedLocking is deprecated, Valhalla assumes it will be removed, and it is not only disabled "by default", but now unusable.

Tier1-3 testing clean

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Testing

|     | Linux x64 | Windows x64 | macOS x64 |
| --- | ----- | ----- | ----- |
| Build | ❌ (2/5 failed) | ❌ (2/2 failed) | ✔️ (2/2 passed) |
| Test (tier1) |    |     |  ❌ (1/9 failed) |

**Failed test tasks**
- [Linux x64 (build hotspot minimal)](https://github.com/MrSimms/valhalla/runs/1281362978)
- [Linux x64 (build hotspot zero)](https://github.com/MrSimms/valhalla/runs/1281362954)
- [Windows x64 (build debug)](https://github.com/MrSimms/valhalla/runs/1281362819)
- [Windows x64 (build release)](https://github.com/MrSimms/valhalla/runs/1281362800)
- [macOS x64 (langtools/tier1)](https://github.com/MrSimms/valhalla/runs/1281588068)

### Issue
 * [JDK-8247299](https://bugs.openjdk.java.net/browse/JDK-8247299): [lworld] Disable UseBiasedLocking by default

### Reviewers
 * [Frederic Parain](https://openjdk.java.net/census#fparain) (@fparain - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/valhalla pull/234/head:pull/234`
`$ git checkout pull/234`

### CODE REVIEW

**Review by fparain — APPROVED** [review]
Looks good to me.

Fred

**Comment by kuksenko** [comment]
Comment. It won't work for arrays properly.
file: oop.inline.hpp  line 207
-  bool oopDesc::is_flatArray() const { return klass()->is_flatArray_klass(); }
+ bool oopDesc::is_flatArray()     const { return mark().is_flat_array(); }

Array maybe locked. So is_flatArray should be like this:
bool oopDesc::is_flatArray()     const { 
  if(mark().is_unlocked()) {
     return mark().is_flat_array(); 
  } else {
     return klass()->is_flatArray_klass();
  }
}

**Pull request closed without merging**
