### PR TITLE
8280270: [lworld] JITs miss some klass initialization checks for defaultvalue

### PR DESCRIPTION
**Pull request by TobiHartmann**
C1 and C2 miss some klass initialization checks for defaultvalue.

Long term, we should add support for patching defaultvalue in C1 (tracked by [JDK-8265067](https://bugs.openjdk.java.net/browse/JDK-8265067)).

Thanks,
Tobias

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8280270](https://bugs.openjdk.java.net/browse/JDK-8280270): [lworld] JITs miss some klass initialization checks for defaultvalue

### Reviewers
 * [Frederic Parain](https://openjdk.java.net/census#fparain) (@fparain - Committer) ⚠️ Review applies to 8d7b2c2e802c1d3cdfb872e5c404e805fa6b63f2

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/611/head:pull/611` \
`$ git checkout pull/611`

Update a local copy of the PR: \
`$ git checkout pull/611` \
`$ git pull https://git.openjdk.java.net/valhalla pull/611/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 611`

View PR using the GUI difftool: \
`$ git pr show -t 611`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/611.diff">https://git.openjdk.java.net/valhalla/pull/611.diff</a>

</details>

### CODE REVIEW

**Review by fparain — APPROVED** [review]
C1 changes look good to me.

Fred

**Comment by TobiHartmann** [comment]
Thanks for the review, Fred!

**Comment by TobiHartmann** [comment]
This patch also contains some fixes for unrelated issues that I found during stress testing.

**Pull request closed without merging**
