### PR TITLE
8242269: [lworld] C2 compilation fails with assert "meet not symmetric"

### PR DESCRIPTION
**Pull request by rwestrel**
This tweaks the type system to fix error triggered by the recent merge.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8242269](https://bugs.openjdk.java.net/browse/JDK-8242269): [lworld] C2 compilation fails with assert "meet not symmetric"

### Reviewers
 * David Simms ([dsimms](@MrSimms) - Committer)
 * Tobias Hartmann ([thartmann](@TobiHartmann) - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/valhalla pull/20/head:pull/20`
`$ git checkout pull/20`

### CODE REVIEW

**Comment by MrSimms** [comment]
Hit integrate if you are done (Tobias is out this week I think, if you were waiting on him)

**Comment by rwestrel** [comment]
I'd like Tobias to take a look at this. Integrating this is not urgent. Tobias disabled the new verification code that triggered the failures. This fixes the failures that that verification code uncovered. They are not new failures. We were just unaware of them.

**Comment by MrSimms** [comment]
> I'd like Tobias to take a look at this. Integrating this is not urgent. 

Fair enough, thank you !

**Pull request closed without merging**
