### PR TITLE
8296950: [lworld] AccessFlags should be specific to class file version

### PR DESCRIPTION
**Pull request by RogerRiggs**
Add java.lang.reflect.AccessFlag.maskToAccessFlags(mask, location, cffv) 
that requests the flags for a specific class file version number.
Update Class.accessFlags() to request the flags for the specific class file format version of the class file.
Update class file format version tests to match.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8296950](https://bugs.openjdk.org/browse/JDK-8296950): [lworld] AccessFlags should be specific to class file version

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - Committer) ⚠️ Review applies to [aca731e7](https://git.openjdk.org/valhalla/pull/808/files/aca731e7f2ee229fc0bba49b7274b1353660e971)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla pull/808/head:pull/808` \
`$ git checkout pull/808`

Update a local copy of the PR: \
`$ git checkout pull/808` \
`$ git pull https://git.openjdk.org/valhalla pull/808/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 808`

View PR using the GUI difftool: \
`$ git pr show -t 808`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/808.diff">https://git.openjdk.org/valhalla/pull/808.diff</a>

</details>

### CODE REVIEW

**Comment by RogerRiggs** [comment]
Please review support for value class access flags of IDENTITY and VALUE and new method to return class file format version specific flags.

**Comment by mlchung** [comment]
This looks okay.  Is there a test to check the access flags on an old class file such that `SUPER` is returned instead of `IDENTITY`?

**Comment by RogerRiggs** [comment]
> This looks okay. Is there a test to check the access flags on an old class file such that `SUPER` is returned instead of `IDENTITY`?

Yes, the change to VersionedLocationsTest does that.

**Comment by mlchung** [comment]
I'm referring to a test that compiles a `.class` with an older class file version and the return access flags from `Class::accessFlags` includes `SUPER`.

**Review by mlchung — APPROVED** [review]

**Pull request closed without merging**
