### PR TITLE
Merge lworld

### PR DESCRIPTION
**Pull request by jatin-bhateja**
Merge latest lworld changes into lworld+vector branch.

Validation Status with this patch:-

-  All the tests under test/hotspot/jtreg/compiler/valhalla/inlinetypes are now passing at various AVX levels.
- No new Vector API jtreg test failure seen.

Best Regards,
Jatin

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla.git pull/929/head:pull/929` \
`$ git checkout pull/929`

Update a local copy of the PR: \
`$ git checkout pull/929` \
`$ git pull https://git.openjdk.org/valhalla.git pull/929/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 929`

View PR using the GUI difftool: \
`$ git pr show -t 929`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/929.diff">https://git.openjdk.org/valhalla/pull/929.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/valhalla/pull/929#issuecomment-1730872831)

### CODE REVIEW

**Comment by XiaohongGong** [comment]
Hi @jatin-bhateja , 

Sorry for my late reply to this PR (just noticed it today)! 

Regarding to the removing of special handling for multifields in C1, it may cause a regression in test `jdk/incubator/vector/VectorRuns.java` and `jdk/incubator/vector/VectorHash.java`. 

Here is the main log: 
```
WARNING: Using incubator modules: jdk.incubator.vector
java.lang.AssertionError: 1024 72
        at VectorRuns.assertEquals(VectorRuns.java:51)
        at VectorRuns.main(VectorRuns.java:46)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:582)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:1570)

JavaTest Message: Test threw exception: java.lang.AssertionError: 1024 72
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: 1024 72
```

I guess the `nof_nonstatic_fields` in the `ciInstanceKlass.cpp` does not contain all the multifields, although https://github.com/openjdk/valhalla/blob/lworld%2Bvector/src/hotspot/share/ci/ciEnv.cpp#L1774 returns `false ` for c1. Because the ci instance is singleton and shared between c1 and c2. So if the instance klass is created and the fields are initialized in c2 compiler thread, its nonstatic fields are just like c2 in c1 which is expected to be vectorized. 

Could you please look at this issue? Running with `"-XX:TieredStopAtLevel=3"` or adding back the original handling in c1 can make these two tests pass. Thanks!

Best Regards,
Xiaohong

**Comment by jatin-bhateja** [comment]
> Hi @jatin-bhateja ,
> 
> Sorry for my late reply to this PR (just noticed it today)!
> 
> Regarding to the removing of special handling for multifields in C1, it may cause a regression in test `jdk/incubator/vector/VectorRuns.java` and `jdk/incubator/vector/VectorHash.java`.
> 
> Here is the main log:
> 
> ```
> WARNING: Using incubator modules: jdk.incubator.vector
> java.lang.AssertionError: 1024 72
>         at VectorRuns.assertEquals(VectorRuns.java:51)
>         at VectorRuns.main(VectorRuns.java:46)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:582)
>         at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
>         at java.base/java.lang.Thread.run(Thread.java:1570)
> 
> JavaTest Message: Test threw exception: java.lang.AssertionError: 1024 72
> JavaTest Message: shutting down test
> 
> STATUS:Failed.`main' threw exception: java.lang.AssertionError: 1024 72
> ```
> 
> I guess the `nof_nonstatic_fields` in the `ciInstanceKlass.cpp` does not contain all the multifields, although https://github.com/openjdk/valhalla/blob/lworld%2Bvector/src/hotspot/share/ci/ciEnv.cpp#L1774 returns `false ` for c1. Because the ci instance is singleton and shared between c1 and c2. So if the instance klass is created and the fields are initialized in c2 compiler thread, its nonstatic fields are just like c2 in c1 which is expected to be vectorized.
> 
> Could you please look at this issue? Running with `"-XX:TieredStopAtLevel=3"` or adding back the original handling in c1 can make these two tests pass. Thanks!
> 
> Best Regards, Xiaohong

Thanks @XiaohongGong , I wanted to give a second though to it. ci model is shared b/w compilers and should ideally be free from specializations, but as you know we have purposefully moved scalarization check upfront to reduce the complexity from field query API. As discussed earlier I am working on max species support and will soon be creating a PR. It will enable us to run entire JTREG suite and uncover regressions.

**Comment by XiaohongGong** [comment]
> Thanks @XiaohongGong , I wanted to give a second though to it. ci model is shared b/w compilers and should ideally be free from specializations, but as you know we have purposefully moved scalarization check upfront to reduce the complexity from field query API. As discussed earlier I am working on max species support and will soon be creating a PR. It will enable us to run entire JTREG suite and uncover regressions.

Yes, I'm also revisiting this part to check whether there are other side effect of current ci design, and I found this tricky issue. Maybe it's better to not consider the multifields in ci stage expect some info passed to compiler. And compiler can choose to do the special handling itself. It's not only to c1 compiler, but also the identity class. We may also think about the scene that the `MultiField` is used in an identity class, although it does not have the usage now.

**Pull request closed without merging**
