### PR TITLE
8292883: [lworld] javac fails to detect class files with invalid access flags

### PR DESCRIPTION
**Pull request by vicente-romero-oracle**
javac is loading a forged class file which declares a primitive class which also has the `identity` flag set. This PR is fixing this bug by issuing an error in such cases.

TIA

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8292883](https://bugs.openjdk.org/browse/JDK-8292883): [lworld] javac fails to detect class files with invalid access flags

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/valhalla pull/754/head:pull/754` \
`$ git checkout pull/754`

Update a local copy of the PR: \
`$ git checkout pull/754` \
`$ git pull https://git.openjdk.org/valhalla pull/754/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 754`

View PR using the GUI difftool: \
`$ git pr show -t 754`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/valhalla/pull/754.diff">https://git.openjdk.org/valhalla/pull/754.diff</a>

</details>

### CODE REVIEW

**Review by fparain — COMMENTED** [review]
I cannot comment on the implementation of the fix, but as the reporter of the issue I can tell that the proposed fix correctly detects the invalid class in the provided use case.

**Comment by vicente-romero-oracle** [comment]
> I cannot comment on the implementation of the fix, but as the reporter of the issue I can tell that the proposed fix correctly detects the invalid class in the provided use case.

@fparain thanks for checking that

**Pull request closed without merging**
