### PR TITLE
8261956: [type-restrictions] Support RestrictedMethod in the interpreter

### PR DESCRIPTION
**Pull request by fparain**
Please review these changes adding support for RestrictedMethod in the interpreter.
Types restrictions are enforced in the following bytecodes:
  - invokevirtual
  - invokestatic
  - invokespecial
  - invokeinterface
  
The changeset also includes a small fix to prevent previous type restrictions related tests to fail.

Thank you,

Fred

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8261956](https://bugs.openjdk.java.net/browse/JDK-8261956): [type-restrictions] Support RestrictedMethod in the interpreter

### Reviewers
 * [David Simms](https://openjdk.java.net/census#dsimms) (@MrSimms - Committer) ⚠️ Review applies to 6b0face9d8385968266ad1db22e9e34afa8bd354
 * [Harold Seigel](https://openjdk.java.net/census#hseigel) (@hseigel - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/valhalla pull/341/head:pull/341`
`$ git checkout pull/341`

### CODE REVIEW

**Review by MrSimms — APPROVED** [review]
Looks good

**Review by hseigel — COMMENTED** [review]
Hi Fred,
Maybe move the classFileParser.cpp code, that checks for the restricted_method attribute, inside of an "if (_major_version >= JAVA_17_VERSION)" conditional?

Thanks, Harold

**Comment by fparain** [comment]
Harold,

Following your suggestion, a class file version check has been added for the RestrictedMethod attribute.

Fred

**Review by hseigel — APPROVED** [review]
The classFileParser.cpp change looks good.  Thanks for changing it.

Harold

**Pull request closed without merging**
