### PR TITLE
8279838: [lworld] PrimitiveObject is dead, long live ValueObject

### PR DESCRIPTION
**Pull request by sadayapalam**
Javac, hotspot and jdk changes to cope with PrimitiveObject in its new avatar as ValueObject

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8279838](https://bugs.openjdk.java.net/browse/JDK-8279838): [lworld] PrimitiveObject is dead, long live ValueObject

### Reviewers
 * @biboudis (no known github.com user name / role) ⚠️ Review applies to 55b23355575985c9843e60b7f0a3eb97b92ac34e
 * [Roger Riggs](https://openjdk.java.net/census#rriggs) (@RogerRiggs - Committer) ⚠️ Review applies to 55b23355575985c9843e60b7f0a3eb97b92ac34e
 * [Frederic Parain](https://openjdk.java.net/census#fparain) (@fparain - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/599/head:pull/599` \
`$ git checkout pull/599`

Update a local copy of the PR: \
`$ git checkout pull/599` \
`$ git pull https://git.openjdk.java.net/valhalla pull/599/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 599`

View PR using the GUI difftool: \
`$ git pr show -t 599`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/599.diff">https://git.openjdk.java.net/valhalla/pull/599.diff</a>

</details>

### CODE REVIEW

**Review by biboudis — APPROVED** [review]
Looks good! 💯

**Review by RogerRiggs — APPROVED** [review]
Core-libs changes look fine.

The \@since tags could be some value other than an actual release.
(1.18 is obsolete already).
Perhaps  "valhalla" or "jep-xxx".

**Comment by forax** [comment]
I've seen 99 being used as transitional version number in several OpenJDK project.

**Review by fparain — APPROVED** [review]
Hotspot changes look good to me.
Thank you for including the Hotspot renaming patch.

Fred

**Comment by sadayapalam** [comment]
Thanks gentlemen, I have made a note of the observation ragarding @since for future use.

**Pull request closed without merging**
