### PR TITLE
8265184: [lworld] [AArch64] Broken fast class init barrier for static calls in c2i adapter

### PR DESCRIPTION
**Pull request by nick-arm**
The tier1 test runtime/clinit/ClassInitBarrier.java fails on the lworld
branch on AArch64.  The particular case that fails is calling a static
native method `A.staticN()` which should block in the c2i adapter until
class A's initialisation is complete but doesn't.

The check for a static method is backwards: the class initialisation
barrier code is executed when the method is *not* static (ANDS will set
the EQ flag if the result is zero).  I'm not sure why it's like this but
fast class initialisation for AArch64 was added after the original
lworld port which also touches generate_i2c2i_adapters so maybe
something got messed up in the merge.

Fix by making the code the same as mainline.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-8265184](https://bugs.openjdk.java.net/browse/JDK-8265184): [lworld] [AArch64] Broken fast class init barrier for static calls in c2i adapter

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/valhalla pull/384/head:pull/384` \
`$ git checkout pull/384`

Update a local copy of the PR: \
`$ git checkout pull/384` \
`$ git pull https://git.openjdk.java.net/valhalla pull/384/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 384`

View PR using the GUI difftool: \
`$ git pr show -t 384`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/valhalla/pull/384.diff">https://git.openjdk.java.net/valhalla/pull/384.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good to me! I think the fix for [JDK-8230962](https://bugs.openjdk.java.net/browse/JDK-8230962) broke this.

**Comment by nick-arm** [comment]
Thanks for the review @TobiHartmann . Would you mind sponsoring this one and #376 ?

**Comment by TobiHartmann** [comment]
Sure!

/sponsor

**Pull request closed without merging**
